---

- name: package install
  apt: name={{ item }} state=present update_cache=yes
  with_items:
      - systemd-container
      - bridge-utils
      - debootstrap

- name: copy systemd-networkd files
  copy: src={{ item }} dest=/etc/systemd/network/{{ item }} mode=0644
  with_items:
      - br0.network
      - br0.netdev

- name: start systemd-networkd
  systemd:
      name: systemd-networkd.service
      enabled: yes
      state: started

- name: copy iptables file
  copy: src=iptables_rule.sh dest=/etc/network/if-pre-up.d/iptables_rule.sh mode=0755
  register: result

- name: configure iptables
  command: /etc/network/if-pre-up.d/iptables_rule.sh
  when: result.changed

- name: copy sysctl file
  copy: src=sysctl.conf dest=/etc/sysctl.conf mode=0644
  register: result

- name: configure sysctl
  command: sysctl -p
  when: result.changed

- name: copy systemd-nspawn@.servece file
  copy: src=systemd-nspawn@.service dest=/etc/systemd/system/systemd-nspawn@.service

- name: make containers directory
  file: path=/root/containers state=directory owner=root group=root mode=0755
  register: result

- name: execute debootstrap
  command: debootstrap --arch amd64 xenial ./master http://archive.ubuntu.com/ubuntu
  when: result.changed

  # - name: setup systemd-machined
  #  file: src=/usr/lib/systemd/system/machines.target dest=/etc/systemd/system/multi-user.target.wants/machines.target state=link
